### ISSUE TITLE
请问一下：在执行之前是否需要安装 quiche

### ISSUE THREAD

**Issue by Jiuyoung** [BarackYoung/quic_rpc#1]
执行项目的时候报错：failed to load the required native library
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: failed to load the required native library
	at io.netty.incubator.codec.quic.Quic.ensureAvailability(Quic.java:78)
	at io.netty.incubator.codec.quic.QuicheQuicSslContext.<init>(QuicheQuicSslContext.java:74)
	at io.netty.incubator.codec.quic.QuicSslContextBuilder.build(QuicSslContextBuilder.java:350)
	at cn.jiuyoung.nettyquicdemo.netty.QuicServerExample.main(QuicServerExample.java:26)
Caused by: java.lang.UnsatisfiedLinkError: io.netty.incubator.codec.quic.Quiche.quiche_enable_debug_logging(Lio/netty/incubator/codec/quic/QuicheLogger;)V
	at io.netty.incubator.codec.quic.Quiche.quiche_enable_debug_logging(Native Method)
	at io.netty.incubator.codec.quic.Quiche.<clinit>(Quiche.java:62)
	at io.netty.incubator.codec.quic.Quic.<clinit>(Quic.java:43)
	... 3 more
```
请问是否要编译安装quicher？

**Comment by Jiuyoung** [comment]
破案了，是m1的netty-codec有问题，在Linux上面运行正常。
